version: '3'

services:
  spotify_db:
    container_name: spotify_db
    domainname: spotify_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - spotify_db:/var/lib/postgresql/data

  init_db:
    container_name: init_db
    domainname: init_db
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DOCKER_HOST=spotify_db
    depends_on:
      - spotify_db
    entrypoint: python docker/init_db.py

volumes:
  spotify_db:
