version: '3'

services:
  spotify_db_tests:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB}

  spotify_tests:
    depends_on:
      - spotify_db_tests
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/opt/app
    entrypoint: pytest # bash -c "tail -f /dev/null"
